/*
All defined actions in application
*/

export type ActionApi =
    "GET_CALENDAR_LIST"
  | "GET_CALENDAR_LIST_SUCCESS"
  | "GET_CALENDAR_LIST_ERROR"
  | "GET_CALENDAR"
  | "GET_CALENDAR_SUCCESS"
  | "GET_CALENDAR_ERROR"
  | "POST_CALENDAR"
  | "POST_CALENDAR_SUCCESS"
  | "POST_CALENDAR_ERROR"
  | "PUT_CALENDAR"
  | "PUT_CALENDAR_SUCCESS"
  | "PUT_CALENDAR_ERROR"
  | "GET_EVENT_LIST"
  | "GET_EVENT_LIST_SUCCESS"
  | "GET_EVENT_LIST_ERROR"
  | "GET_EVENT"
  | "GET_EVENT_SUCCESS"
  | "GET_EVENT_ERROR"
  | "POST_EVENT"
  | "POST_EVENT_SUCCESS"
  | "POST_EVENT_ERROR"
  | "PUT_EVENT"
  | "PUT_EVENT_SUCCESS"
  | "PUT_EVENT_ERROR"
  | "DELETE_EVENT"
  | "DELETE_EVENT_SUCCESS"
  | "DELETE_EVENT_ERROR";

export const ActionApi: {[key: string]: ActionApi} = {
  GET_CALENDAR_LIST: "GET_CALENDAR_LIST",
  GET_CALENDAR_LIST_SUCCESS: "GET_CALENDAR_LIST_SUCCESS",
  GET_CALENDAR_LIST_ERROR: "GET_CALENDAR_LIST_ERROR",
  GET_CALENDAR: "GET_CALENDAR",
  GET_CALENDAR_SUCCESS: "GET_CALENDAR_SUCCESS",
  GET_CALENDAR_ERROR: "GET_CALENDAR_ERROR",
  POST_CALENDAR: "POST_CALENDAR",
  POST_CALENDAR_SUCCESS: "POST_CALENDAR_SUCCESS",
  POST_CALENDAR_ERROR: "POST_CALENDAR_ERROR",
  PUT_CALENDAR: "PUT_CALENDAR",
  PUT_CALENDAR_SUCCESS: "PUT_CALENDAR_SUCCESS",
  PUT_CALENDAR_ERROR: "PUT_CALENDAR_ERROR",
  GET_EVENT_LIST: "GET_EVENT_LIST",
  GET_EVENT_LIST_SUCCESS: "GET_EVENT_LIST_SUCCESS",
  GET_EVENT_LIST_ERROR: "GET_EVENT_LIST_ERROR",
  GET_EVENT: "GET_EVENT",
  GET_EVENT_SUCCESS: "GET_EVENT_SUCCESS",
  GET_EVENT_ERROR: "GET_EVENT_ERROR",
  POST_EVENT: "POST_EVENT",
  POST_EVENT_SUCCESS: "POST_EVENT_SUCCESS",
  POST_EVENT_ERROR: "POST_EVENT_ERROR",
  PUT_EVENT: "PUT_EVENT",
  PUT_EVENT_SUCCESS: "PUT_EVENT_SUCCESS",
  PUT_EVENT_ERROR: "PUT_EVENT_ERROR",
  DELETE_EVENT: "DELETE_EVENT",
  DELETE_EVENT_SUCCESS: "DELETE_EVENT_SUCCESS",
  DELETE_EVENT_ERROR: "DELETE_EVENT_ERROR"
}

export type ActionEntities =
    "CREATE_CALENDAR"
  | "CREATE_TEACH_EVENT"
  | "UPDATE_TEACH_EVENT"
  | "DELETE_TEACH_EVENT"
  | "CLEAR_ENTITIES"
  | "CLEAR_EVENTS";

export const ActionEntities: {[key: string]: ActionEntities} = {
  CREATE_CALENDAR: "CREATE_CALENDAR",
  CREATE_TEACH_EVENT: "CREATE_TEACH_EVENT",
  UPDATE_TEACH_EVENT: "UPDATE_TEACH_EVENT",
  DELETE_TEACH_EVENT: "DELETE_TEACH_EVENT",
  CLEAR_ENTITIES: "CLEAR_ENTITIES"
};

export type ActionUI =
    "SELECT_ONE"
  | "SELECT_ALL"
  | "SET_VIEW"
  | "CLEAR_PRESETS"
  | "ERROR"
  | "CLOSE_ERROR";

export const ActionUI: {[key: string]: ActionUI} = {
  SELECT_ONE: "SELECT_ONE",
  SELECT_ALL: "SELECT_ALL",
  SET_VIEW: "SET_VIEW",
  CLEAR_PRESETS: "CLEAR_PRESETS",
  ERROR: "ERROR",
  CLOSE_ERROR: "CLOSE_ERROR",
}

export type ActionResource =
    "CREATE_CALENDAR_RESOURCE"
  | "CLEAR_RESOURCES"
  | "REMOVE_CALENDAR_RESOURCE"
  | "CREATE_EVENT_RESOURCE"
  | "REMOVE_EVENT_RESOURCE";

export const ActionResource: {[key: string]: ActionResource} = {
  CREATE_CALENDAR_RESOURCE: "CREATE_CALENDAR_RESOURCE",
  CLEAR_RESOURCES: "CLEAR_RESOURCES",
  REMOVE_CALENDAR_RESOURCE: "REMOVE_CALENDAR_RESOURCE",
  CREATE_EVENT_RESOURCE: "CREATE_EVENT_RESOURCE",
  REMOVE_EVENT_RESOURCE: "REMOVE_EVENT_RESOURCE"
}

export type ActionType =
    ActionApi
  | ActionEntities
  | ActionResource
  | ActionUI
  | "GLOBAL"
  | "NULL";

export interface Action {
  type: ActionType;
}
